language: go

go:
  - "1.10"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libasound2-dev
      - libglew-dev # required by headless-gl.
      - libgles2-mesa-dev
      - libalut-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev

# gl module is not available (2016-05-18)
#
# before_install:
#  - export NODE_PATH=$(npm config get prefix)/lib/node_modules
#  - npm install --global gl

install:
  - go get -t -v github.com/hajimehoshi/ebiten/...
  - go get github.com/gopherjs/gopherjs
  - go get github.com/gopherjs/webgl
  - go get -tags example github.com/hajimehoshi/ebiten/examples/...

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - test -z $(gofmt -s -l $GOPATH/src/github.com/hajimehoshi/ebiten)
  - go build -tags example -v github.com/hajimehoshi/ebiten/examples/...
  - go test -v github.com/hajimehoshi/ebiten/...
  - go test -tags=example -v github.com/hajimehoshi/ebiten/examples/...
  - gopherjs build --tags example -v github.com/hajimehoshi/ebiten/examples/blocks

# Looks like testing GL on node is hard.
# - gopherjs test -v github.com/hajimehoshi/ebiten github.com/hajimehoshi/ebiten/internal/graphics

notifications:
  email:
    recipients:
      - hajimehoshi@gmail.com
